# Generated by Django 2.2.3 on 2019-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='preparation_time',
            field=models.IntegerField(),
        ),
    ]
