# Generated by Django 2.2.3 on 2019-08-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
